select  DISTINCT type_desc  FROM sys.sql_modules m
INNER JOIN sys.objects o ON m.object_id=o.object_id



VIEW
SQL_TABLE_VALUED_FUNCTION
SQL_STORED_PROCEDURE
SQL_INLINE_TABLE_VALUED_FUNCTION
SQL_TRIGGER
SQL_SCALAR_FUNCTION